### ISSUE TITLE
Warnings "unary operator expected"

### ISSUE THREAD

**Issue by wolfkang** [juangacovas/rsnapshot-mysql#1]
Hi,
I got these warnings.

> /efs/mysql/rsnapshot-mysql.sh: line 362: [: ==: unary operator expected
> /efs/mysql/rsnapshot-mysql.sh: line 365: [: ==: unary operator expected
> /efs/mysql/rsnapshot-mysql.sh: line 368: [: ==: unary operator expected

Please check this out.
Thanks.

**Comment by juangacovas** [comment]
Hello, I've just updated the script. Please try again, I tested it.
